import Head from "next/head";
import Image from "next/image";
import InputTodoForm from "../components/InputTodoForm";
import TodoList from "../components/TodoList";
import styles from "../styles/Home.module.css";

//https://tech-blog.rakus.co.jp/entry/20220928/vercel

export default function Home() {
  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <div className="flex justify-center items-center h-screen">
        <InputTodoForm />
      </div>
    </div>
  );
}
